-- Livres de la Bible (Crampon 1923 — canon catholique complet), à coller après schema_bible.sql
insert into bible_livres (code, nom, testament, canon, ordre, nombre_chapitres) values
  ('gn', 'Genèse', 'ancien', 'commun', 1, 50),
  ('ex', 'Exode', 'ancien', 'commun', 2, 40),
  ('lv', 'Lévitique', 'ancien', 'commun', 3, 27),
  ('nb', 'Nombres', 'ancien', 'commun', 4, 36),
  ('dt', 'Deutéronome', 'ancien', 'commun', 5, 34),
  ('jos', 'Josué', 'ancien', 'commun', 6, 24),
  ('jg', 'Juges', 'ancien', 'commun', 7, 21),
  ('rt', 'Ruth', 'ancien', 'commun', 8, 4),
  ('1s', '1 Samuel', 'ancien', 'commun', 9, 31),
  ('2s', '2 Samuel', 'ancien', 'commun', 10, 24),
  ('1r', '1 Rois', 'ancien', 'commun', 11, 22),
  ('2r', '2 Rois', 'ancien', 'commun', 12, 25),
  ('1ch', '1 Chroniques', 'ancien', 'commun', 13, 29),
  ('2ch', '2 Chroniques', 'ancien', 'commun', 14, 36),
  ('esd', 'Esdras', 'ancien', 'commun', 15, 10),
  ('ne', 'Néhémie', 'ancien', 'commun', 16, 13),
  ('tb', 'Tobie', 'ancien', 'deuterocanonique', 17, 14),
  ('jdt', 'Judith', 'ancien', 'deuterocanonique', 18, 16),
  ('est', 'Esther', 'ancien', 'commun', 19, 16),
  ('1m', '1 Maccabées', 'ancien', 'deuterocanonique', 20, 16),
  ('2m', '2 Maccabées', 'ancien', 'deuterocanonique', 21, 15),
  ('jb', 'Job', 'ancien', 'commun', 22, 42),
  ('ps', 'Psaumes', 'ancien', 'commun', 23, 150),
  ('pr', 'Proverbes', 'ancien', 'commun', 24, 31),
  ('qo', 'Ecclésiaste', 'ancien', 'commun', 25, 12),
  ('ct', 'Cantique des cantiques', 'ancien', 'commun', 26, 8),
  ('sg', 'Sagesse', 'ancien', 'deuterocanonique', 27, 19),
  ('si', 'Siracide (Ecclésiastique)', 'ancien', 'deuterocanonique', 28, 51),
  ('is', 'Isaïe', 'ancien', 'commun', 29, 66),
  ('jr', 'Jérémie', 'ancien', 'commun', 30, 52),
  ('lm', 'Lamentations', 'ancien', 'commun', 31, 5),
  ('ba', 'Baruch', 'ancien', 'deuterocanonique', 32, 6),
  ('ez', 'Ézéchiel', 'ancien', 'commun', 33, 48),
  ('dn', 'Daniel', 'ancien', 'commun', 34, 14),
  ('os', 'Osée', 'ancien', 'commun', 35, 14),
  ('jl', 'Joël', 'ancien', 'commun', 36, 4),
  ('am', 'Amos', 'ancien', 'commun', 37, 9),
  ('ab', 'Abdias', 'ancien', 'commun', 38, 1),
  ('jon', 'Jonas', 'ancien', 'commun', 39, 4),
  ('mi', 'Michée', 'ancien', 'commun', 40, 7),
  ('na', 'Nahum', 'ancien', 'commun', 41, 3),
  ('ha', 'Habacuc', 'ancien', 'commun', 42, 3),
  ('so', 'Sophonie', 'ancien', 'commun', 43, 3),
  ('ag', 'Aggée', 'ancien', 'commun', 44, 2),
  ('za', 'Zacharie', 'ancien', 'commun', 45, 14),
  ('ml', 'Malachie', 'ancien', 'commun', 46, 3),
  ('mt', 'Matthieu', 'nouveau', 'commun', 47, 28),
  ('mc', 'Marc', 'nouveau', 'commun', 48, 16),
  ('lc', 'Luc', 'nouveau', 'commun', 49, 24),
  ('jn', 'Jean', 'nouveau', 'commun', 50, 21),
  ('ac', 'Actes des Apôtres', 'nouveau', 'commun', 51, 28),
  ('rm', 'Romains', 'nouveau', 'commun', 52, 16),
  ('1co', '1 Corinthiens', 'nouveau', 'commun', 53, 16),
  ('2co', '2 Corinthiens', 'nouveau', 'commun', 54, 13),
  ('ga', 'Galates', 'nouveau', 'commun', 55, 6),
  ('ep', 'Éphésiens', 'nouveau', 'commun', 56, 6),
  ('ph', 'Philippiens', 'nouveau', 'commun', 57, 4),
  ('col', 'Colossiens', 'nouveau', 'commun', 58, 4),
  ('1th', '1 Thessaloniciens', 'nouveau', 'commun', 59, 5),
  ('2th', '2 Thessaloniciens', 'nouveau', 'commun', 60, 3),
  ('1tm', '1 Timothée', 'nouveau', 'commun', 61, 6),
  ('2tm', '2 Timothée', 'nouveau', 'commun', 62, 4),
  ('tt', 'Tite', 'nouveau', 'commun', 63, 3),
  ('phm', 'Philémon', 'nouveau', 'commun', 64, 1),
  ('he', 'Hébreux', 'nouveau', 'commun', 65, 13),
  ('jc', 'Jacques', 'nouveau', 'commun', 66, 5),
  ('1p', '1 Pierre', 'nouveau', 'commun', 67, 5),
  ('2p', '2 Pierre', 'nouveau', 'commun', 68, 3),
  ('1jn', '1 Jean', 'nouveau', 'commun', 69, 5),
  ('2jn', '2 Jean', 'nouveau', 'commun', 70, 1),
  ('3jn', '3 Jean', 'nouveau', 'commun', 71, 1),
  ('jude', 'Jude', 'nouveau', 'commun', 72, 1),
  ('ap', 'Apocalypse', 'nouveau', 'commun', 73, 22)
on conflict (code) do nothing;
